---
output: pdf_document
fontsize: 12pt
---

# Where are you safest from parking tickets in Seattle?
### Police issue the fewest tickets on Sundays, in the afternoon/evening, and outside of the city center  

```{r, warning=FALSE, message=FALSE, include=FALSE}
rm(list = ls())

library(tidyverse)
library(ggthemes)
library(scales)
library(lubridate)

# devtools::install_github("dkahle/ggmap")

library(ggmap)

register_google(key = 'AIzaSyB96DWzULF-BPebTXa-oJU-fzs7Cwo751Y')

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

parking <- read.csv('https://goo.gl/nNAuDy') %>% 
  filter(
    event_clearance_subgroup %in% 'PARKING VIOLATIONS' & 
      ! district_sector %in% c('NULL', '99')
    ) %>%
    transmute(
    event_clearance_date
    , event_clearance_ampm
    , day_of_week = event_clearance_date %>% 
           ymd() %>% wday()
   , day_name = ifelse(day_of_week %in% 1, 'Sun', 
                ifelse(day_of_week %in% 2, 'Mon', 
                ifelse(day_of_week %in% 3, 'Tues',
                ifelse(day_of_week %in% 4, 'Wed',
                ifelse(day_of_week %in% 5, 'Thur',
                ifelse(day_of_week %in% 6, 'Fri', 'Sat'))))))
   , district_sector
   , longitude
   , latitude
         )

timeline <- parking %>%
  group_by(day_of_week, event_clearance_date, day_name, event_clearance_ampm) %>%
  summarise(n = n()) %>%
  filter(! day_of_week %in% NA) %>%
  ungroup %>%
  group_by(day_name, day_of_week, event_clearance_ampm) %>%
  summarise(n = n()) %>% 
  ungroup %>%
  ggplot(aes(x = reorder(day_name, - day_of_week), y = n, fill = event_clearance_ampm)) +
  geom_bar(stat = 'identity', position = 'dodge') +  
  xlab('') + 
  ylab('Parking Tickets (#)') + 
  theme_classic() + 
  coord_flip() +
  theme(legend.position = 'top') +
  labs(fill = 'Time of Day')

seattle_coords <- c(-122.335167, 47.608013)
seattle <- get_googlemap(seattle_coords, zoom = 12)

overlay <- stat_density2d(
  aes(
    x = longitude, y = latitude
    , fill = ..level.., alpha = (..level..) * .25)
    , size = 2, bins = 8
    , data = parking
    , geom = "polygon"
  )
```

```{r,  warning=FALSE, message=FALSE, fig.height = 4, fig.width = 7, echo = FALSE}
multiplot(timeline, ggmap(seattle, extent = "device") + overlay + theme(legend.position = 'none'), cols = 2)
```
\newline
\newline
\newline
\newline
  
\centerline{\textbf{Top and bottom 3 districts for parking tickets}}  
```{r,  warning=FALSE, message=FALSE, echo = FALSE, results = 'asis'}
parking %>%
  group_by(day_name, district_sector) %>%
  summarise(n = n()) %>%
  spread(day_name, n) %>%
  mutate(avg = ((Sun + Mon + Tues + Wed + Thur + Fri + Sat) / 7) %>% round(2)) %>%
  arrange(desc(avg)) %>%
  mutate(Frequency = 'Most Tickets') %>% 
  select(district_sector, Frequency, Sun, Mon, Tues, Wed, Thur, Fri, Sat) %>%
  rename(`District Sector` = district_sector) %>%
  slice(1:3) %>% 
  bind_rows(
    parking %>%
      group_by(day_name, district_sector) %>%
      summarise(n = n()) %>%
      spread(day_name, n) %>%
      mutate(avg = ((Sun + Mon + Tues + Wed + Thur + Fri + Sat) / 7) %>% round(2)) %>%
      arrange(desc(avg)) %>%
      mutate(Frequency = 'Fewest Tickets') %>% 
      select(district_sector, Frequency, Sun, Mon, Tues, Wed, Thur, Fri, Sat) %>%
      rename(`District Sector` = district_sector) %>%
      slice(15:17)
  ) %>%
  knitr::kable()
```
