---
title: "Introduction to Data Processing and Visualization Design in R"
subtitle: "Autumn 2026"
output: html_document
---

<style type="text/css">

h1.title {
  font-size: 38px;
  color: Black;
  text-align: center;
}

h3.subtitle {
  font-size: 30px;
  color: Black;
  text-align: center;
}
h4.author { 
    font-size: 18px;
  color: Black;
  text-align: center;
}
h4.date { 
  font-size: 18px;
  color: Black;
  text-align: center;
}
</style> 

<br>

## Schedule  

**Time: 5:30-8:20pm**  
**Class Dates: 10/6, 10/13, 10/20, 10/27**  
**Location: [PAR 220](https://www.washington.edu/maps/#!/par)** 

## Instructors

**Graham Bearden (gbearden@uw.edu)**    

## Course Overview

This is an introductory course designed for new R programmers. You will learn the fundamental skills required to prepare, analyze and visualize data in R. You will also build a foundation for additional training in R and general applied data analysis.

Course materials are prepared to offer a survey of selected R functionality. We will also talk about how AI assistants fit into R programming; how much you use them in class depends on your level of interest. Students interested in more sophisticated or specialized programming than what is taught in this course are encouraged to seek additional opportunities to apply their skills.

This is an applied course that focuses on successful execution of code. While students should consider theory, style, and efficiency of R programming, getting the job done right will be the first priority.  

## Course Expectations

- Attend four classes. Class dates are 10/6, 10/13, 10/20, 10/27. A full class is 2 hours and 50 minutes, breaks included.
- Submit a memo created in R by 10/30 or before. 
    + The memo must include either (a) two data visualizations or (b) one data visualization and one table made in R. Start from one of the [memo templates](https://github.com/gbearden/r_course_evans_school/tree/master/memo_templates) and see the [example memo](https://gbearden.github.io/r_course_evans_school/memo_templates/example_memo.html).
    + This course teaches data analysis tools, not data analysis, so you do not need to write up an analysis. The memo's text can be placeholder text, like the "lorem ipsum" text in the example memo.
    + Visualizations should be "stakeholder-ready" (see [example plots](https://github.com/gbearden/r_course_evans_school/tree/master/plots)). A stakeholder-ready visualization:
        - Has a descriptive plot title
        - Has labeled axes
        - Uses a theme
        - Does not include `NA`s in the plot (in the geom or the legend)
 
## Accommodations

Washington State law requires that UW develop a policy for accommodation of student absences or significant hardship due to reasons of faith or conscience, or for organized religious activities. The UW’s policy, including more information about how to request an accommodation, is available at [Religious Accommodations Policy](https://registrar.washington.edu/staff-faculty/religious-accommodations-policy/). Accommodations must be requested within the first two weeks of this course using the [Religious Accommodations Request Form](https://registrar.washington.edu/students/religious-accommodations-request/). 

Please let me know if you need any specific accommodations related to religious observation or otherwise. I will help provide accommodations in accordance with Evans School policy and Washington State law.

## Schedule

#### October 6

The first class will focus on the basics of R. Students will learn about key R concepts like data types and the anatomy of a function, how to read (import) and write (export) data, and the essentials of writing successful code.

We will also begin to explore data summary techniques and troubleshooting tactics that students can use to solve coding errors. 

At the end of first class, students should be familiar with the R interface, know how to perform basic operations, calculate summary statistics, and walk through a series of steps to troubleshoot code.

Helpful materials: [example .R file](https://github.com/gbearden/r_course_evans_school/blob/master/notes/example_script.R), [base R cheat sheet](https://rstudio.github.io/cheatsheets/base-r.pdf)

#### October 13

The second class will focus on data processing. We will use a variety of methods to manipulate data and prepare it for analysis. The `tidyverse` will be emphasized. Students will learn how to manipulate data at various levels, including at the dataset-level, the variable-level, and the value-level.

At the end of second class, students should possess skills necessary to transform datasets so that data are suitable for analysis.

Helpful materials: [data transformation cheat sheet](https://github.com/rstudio/cheatsheets/blob/main/data-transformation.pdf), [data tidying cheat sheet](https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf), [R for Stata users](https://www.matthieugomez.com/statar/manipulate-data.html)

#### October 20

The third class will focus on data visualization. We will use `ggplot`, a visualization library that is part of the `tidyverse`, to build many types of plots. The modularity of `ggplot` plotting functions will be emphasized as will the distinction between visualizing aggregated and non-aggregated data.

At the end of third class, students should be able to produce a standard set of plots and manipulate plot aesthetics.

Helpful materials: [data visualization cheat sheet](https://github.com/rstudio/cheatsheets/blob/main/data-visualization-2.1.pdf), [Coolors](https://coolors.co/)

#### October 27

The fourth class will build on the skills students learned in previous lessons, introducing additional data visualization and data processing skills used to better work with strings and reshape data. 

At the end of the fourth class, students should be able to prepare data for analysis and "stakeholder-ready" visualization using a broad set of coding skills.

## Data

We will use the datasets below in our workshop. ([Here](https://github.com/gbearden/r_course_evans_school/blob/master/data/process_course_data.r) is code to prepare the temperature and Airbnb data.)

* [Global Temperatures Source](https://www.kaggle.com/datasets/berkeleyearth/climate-change-earth-surface-temperature-data)
  * [Global Temperatures Dataset](https://raw.githubusercontent.com/gbearden/r_course_evans_school/master/data/global_temperatures.csv)
* [Seattle Airbnb Source](https://www.kaggle.com/datasets/shanelev/seattle-airbnb-listings)  
  * [Seattle Airbnb Dataset](https://raw.githubusercontent.com/gbearden/r_course_evans_school/master/data/seattle_airbnb.csv)
* [MBA Admissions Source](https://www.kaggle.com/datasets/taweilo/mba-admission-dataset) (synthetic data based on the Wharton Class of 2025)
  * [MBA Admissions Dataset](https://raw.githubusercontent.com/gbearden/r_course_evans_school/master/data/mba_admissions.csv)
* [American Community Survey (ACS)](https://www.census.gov/programs-surveys/acs) from the U.S. Census Bureau
  * Pulled directly into R with the [tidycensus](https://walker-data.com/tidycensus/) package (requires a free Census API key; see below)

## Install R

If you have not downloaded R and RStudio already, use the links below to set up your machines.

* Install R [on a Mac with a silicon chip](https://cloud.r-project.org/bin/macosx/sonoma-arm64/base/R-4.6.1-arm64.pkg), [on a Mac with an Intel chip](https://cloud.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.6.1-x86_64.pkg), or [on a PC](https://cloud.r-project.org/bin/windows/base/R-4.6.1-win.exe)
* Install RStudio [on a Mac](https://download1.rstudio.org/electron/macos/RStudio-2026.09.0-174.dmg) or [on a PC](https://download1.rstudio.org/electron/windows/RStudio-2026.09.0-174.exe)
* Request a free [Census API key](https://api.census.gov/data/key_signup.html) before the first class. The key arrives by email and lets you pull Census data into R with `tidycensus`.

## AI Assistants

AI assistants are optional. Every exercise and the final assignment can be completed without one.

AI assistants are helpful when troubleshooting, documenting, and writing R code. If you would like to use one, [Claude](https://claude.com/), [ChatGPT](https://chatgpt.com/), and [GitHub Copilot](https://github.com/features/copilot) all work well with R, as do many other AI assistants.

You can use the desktop app, web browser, or a free code editor. [VS Code](https://code.visualstudio.com/) is a free code editor that runs R code and works with AI assistants such as GitHub Copilot and Claude, so the assistant can read and edit your code directly. If you would like to try it, follow [this guide](https://gbearden.github.io/r_course_evans_school/help/vscode/) to install and set up VS Code.

If you do use an AI assistant, do not paste sensitive or confidential data into it.

## Reference Materials

R community members produce valuable content to help you learn how to program in R. Here are some of my favorite resources that you might find useful as a new R programmer:

* [RStudio](https://posit.co/). The R IDE (integrated development environment) we will use in the course.
* [tidyverse](https://www.tidyverse.org/). The launch page for tidyverse.
* [R for Data Science (2e)](https://r4ds.hadley.nz/). A free online book by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund. The best next step after this course.
* [Cheat sheets](https://posit.co/resources/cheatsheets/) (often these are available in other languages in case that's useful)
    + [Base R](https://rstudio.github.io/cheatsheets/base-r.pdf). This is useful to get started.
    + [Data transformation](https://rstudio.github.io/cheatsheets/data-transformation.pdf). I use this all the time when working with dplyr.
    + [Data tidying](https://rstudio.github.io/cheatsheets/tidyr.pdf). If the dplyr cheat sheet were Batman, the tidyr cheat sheet is Robin.
    + [Data visualization](https://rstudio.github.io/cheatsheets/data-visualization.pdf). A great quick-reference for the ggplot library.
    + [R Markdown](https://rstudio.github.io/cheatsheets/rmarkdown.pdf). A useful reference for using R Markdown.
    + [Lubridate](https://rstudio.github.io/cheatsheets/lubridate.pdf). Dates in R are a pain in the butt. This cheat sheet and the lubridate library will make your life easier.  
* [Karl Broman on data organization](https://kbroman.org/dataorg/). Prepare your data according to Karl's recommendations and R will become a lot easier. (The tip is relevant to all other KB recommendations.)
* [Jose Manuel Magallanes on data collection and organization](https://www.amazon.com/Introduction-Science-Social-Policy-Research/dp/1107540259/ref=sr_1_1?ie=UTF8&qid=1504135785&sr=8-1&keywords=jose+manuel+magallanes). Jose taught the Computational Thinking for Governance Analytics course at the Evans School. He published this book a few years ago.
* [R Bloggers](https://www.r-bloggers.com/). All things R. Folks from various industries - many of whom are super smart with impressive R experience - share tips, tricks, and anecdotes here.
* [stackoverflow](https://stackoverflow.com/questions/tagged/r). This is where you come when you get stuck. Google the problem you are having and you'll see a possible solution on the stackoverflow site. Guaranteed.
* [Google R Style Guide](https://google.github.io/styleguide/Rguide.html). Your code can get really messy really quickly. This guide can help.
* [Coolors](https://coolors.co/). I love this site. It is great inspiration when building plots.
* [GitHub](https://github.com/). If you're serious about any sort of programming, you should create a GitHub account.
* [RStudio Cloud setup](https://github.com/gbearden/r_course_evans_school/blob/master/rcloud_setup.md)  
